version: '3'
services:
  golang:
    build:
      context: ..
      target: development
    environment:
      - TZ=Asia/Tokyo
      - SHELL=/bin/bash
    ports:
      - 8080:8080
    tty: true
    volumes:
      - ..:/workspace:cached